### ISSUE TITLE
[User feedback] Import file

### ISSUE THREAD

**Issue by EyeSeeTeaBotTest** [EyeSeeTea/Bulk-Load-blessed#24]
## dhis2

Username: nmcpirn

## Browser
- Name: Mozilla
- Version: 5.0 (Windows)
- Platform: Win32

## User report
URL: https://extranet.who.int/dhis2/api/apps/Bulk-Load/index.html#/import

I could not import file

![See screenshot here]( https://raw.githubusercontent.com/EyeSeeTeaBotTest/snapshots/master/screenshot-1599254704217410776.png )

**Comment by ifoche** [comment]
A couple of issues were detected with this Excel templates:
- The templates had the coordinates filled in. It seems that if any coordinate is introduced, it has to be using a concrete format. A validation is run against them and if it doesn't work then it just fails. Didn't we deactivate the validation of coordinates?
- If the format of a percentage cell is changed into percentage instead of what we're using when generating the template, when submitting that template back to the system it fails with a 409 error, but accepts the data (reading the import summary you discover that it was just the percentage DEs who were rejected because of its format)

Apart from that, this issue itself has been solved with the workarounds of:
- Removing coordinates from the spreadsheet
- Changing the format to numeric from 0-100 range

Maybe this issue could be closed and 2 different issues created to remove the coordinates validation if we're not doing anything with them anymore and to add a validation for the cells format when possible

**Comment by adrianq** [comment]
Coordinate validation is currently hidden as it was not working properly. Other errors cannot be reproduced
